# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: CI - Build with Ant

on:
  workflow_dispatch

jobs:
  XSBuild:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
        ref: '${{GITHUB.REF}}'
        
    - name: Inizialize Variables (Version, Release)
      shell: powershell
      id: variables
      run: |
          $AppProps = convertfrom-stringdata (get-content .\amp_pos\installx\builder\ant.install.properties -raw)
          $AppProps.'cust.version'
          echo "::set-output name=VERSION_NAME::$(echo $AppProps.'cust.version')"
          echo "::set-output name=RELEASE::$(echo $AppProps.'x.version')"
          
    - name: Extract LFS
      shell: powershell
      run: Expand-Archive -LiteralPath './amp_zip-release/release_${{ steps.variables.outputs.RELEASE }}.7z' -DestinationPath ./../../../releases/${{ steps.variables.outputs.RELEASE }}
    
    - name: Build with Ant
      run: ant -f amp/jenkins-build.xml distribution
    
    - name: Set current branch
      shell: powershell 
      id: set-current-branch
      run: |
            $branchName = "${{GITHUB.REF}}".Split("/")["${{GITHUB.REF}}".Split("/").Length -1]
            echo "::set-output name=CURRENT_BRANCH::$(echo $branchName)"
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: XStore_${{ steps.set-current-branch.outputs.CURRENT_BRANCH }}_${{ steps.variables.outputs.VERSION_NAME }}
