# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: CI - Build with Ant

on:
  workflow_dispatch:
#    inputs:
#      versionName:
#        description: 'Name of version  (ie 5.5.0)'
#        required: true

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Extract LFS
      shell: pwsh
      run: Expand-Archive -LiteralPath 'C:\...\...\...\test.zip' -DestinationPath C:\...\...\Desktop
    - name: Extract version
      shell: pwsh
      run: 
    - name: Build with Ant
      run: ant -f amp/jenkins-build.xml distribution
    - uses: bhowell2/github-substring-action@v1
      id: branch
      with:
        value: "${{GITHUB.REF}}"
        index_of_str: "refs/heads/"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: XStore_${{ steps.branch.outputs.substring }}_${{ github.event.inputs.versionName }}
