Write-Host ================================================
Write-Host
Write-Host Amplifon Update Permissions Script
Write-Host
Write-Host ================================================

$APP_ROOT="C:\PROGRA~1\app"
$JRE_DIR="$APP_ROOT\jre"
$XSTORE_DIR="$APP_ROOT\xstore"
$XSTORE_MOBILE_DIR="$APP_ROOT\xstore-mobile"
$XSTOREDB_DIR="$APP_ROOT\xstoredb"
$XENV_DIR="$APP_ROOT\environment"
$UPDATE_DIR="$APP_ROOT\updates"
$BACKUP_DIR="$APP_ROOT\BACKUPxstore"

Write-Host Application root directory is $APP_ROOT
Write-Host JRE directory is $JRE_DIR
Write-Host Xstore root directory is $XSTORE_DIR
Write-Host Xstore Mobile root directory is $XSTORE_MOBILE_DIR
Write-Host Xstore DB directory is $XSTOREDB_DIR
Write-Host Xenvironment root directory is $XENV_DIR
Write-Host Xenv update directory is $UPDATE_DIR
Write-Host Backup Xstore directory is $BACKUP_DIR

Write-Host ================================================
Write-Host Reset permissions to default
Write-Host ================================================

Invoke-Expression "icacls $XSTORE_DIR /t /q /c /reset"
Invoke-Expression "icacls $JRE_DIR /t /q /c /reset"
Invoke-Expression "icacls $XSTORE_MOBILE_DIR /t /q /c /reset"
Invoke-Expression "icacls $XSTOREDB_DIR /t /q /c /reset"
Invoke-Expression "icacls $XENV_DIR /t /q /c /reset"
Invoke-Expression "icacls $UPDATE_DIR /t /q /c /reset"
Invoke-Expression "icacls $BACKUP_DIR /t /q /c /reset"

Write-Host ================================================
Write-Host Add RXM permissions for Authenticated Users
Write-Host ================================================

Invoke-Expression "icacls $JRE_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $XSTORE_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $XSTORE_MOBILE_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $XSTOREDB_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $XENV_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $UPDATE_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
Invoke-Expression "icacls $BACKUP_DIR /grant '*S-1-5-11:(OI)(CI)RXM' /t /c /inheritance:e"
