name: Deploy

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      branchName:
        description: 'Name of branch to deploy'
        required: true
#      destinationEnv:
#        description: 'Name of destination Branch'
#        required: true
        
jobs:
  GetDownloadURL:
    runs-on: ubuntu-latest
    
    outputs:
      url: ${{ steps.url.outputs.URL }}
      artifact: ${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}
    
    steps:
      - name: Set current artifact name
        id: current-artifact
        shell: bash
        run: |
              echo "::set-output name=CURRENT_ARTIFACT::$(echo XStore_${{ github.event.inputs.branchName }}_${{ github.event.inputs.versionName }})"
      
      - name: Get latest artifact id
        id: max_id
        shell: bash
        run: |
              echo "::set-output name=MAX_ID::$(curl -fs https://api.github.com/repos/${{github.repository}}/actions/artifacts |
              jq '[ .artifacts[] | select(.name == "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}" and .expired == false) | .id ] | max')
              
      - name: Get lastest artifact url
        id: url
        shell: bash
        run: |
              echo "::set-output name=URL::$(curl -fs https://api.github.com/repos/${{github.repository}}/actions/artifacts |
              jq '.artifacts[] | select(.id == ${{ steps.max_id.outputs.MAX_ID }} and .expired == false) | .archive_download_url')
        
      
  DeployXOffice:
    runs-on: ubuntu-latest
    needs: GetDownloadURL
    
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Download Artifact
        if: ${{needs.GetDownloadURL.outputs.url}} != ""
        shell: bash
        run: |
              #!/bin/bash
              mkdir ./output
              cd ./output
              curl -u username[:{personalaccesstoken}] -o "${{needs.GetDownloadURL.outputs.artifact}}.zip" "${{needs.GetDownloadURL.outputs.url}}"
              
      - name: Deploy XOffice
        if: ${{needs.GetDownloadURL.outputs.url}} != ""
        shell: bash
        run: .\shell_scripts\xo_setup.sh ${{ github.event.inputs.versionName }} ${{ github.event.inputs.branchName }}
      
  DeployXStore:
    runs-on: windows-latest
    needs: [GetDownloadURL, DeployXOffice]
    
    steps:
      - uses: actions/checkout@v2
        with:
           lfs: 'true'
      - name: Download Artifact
        if: ${{needs.GetDownloadURL.outputs.url}} != ""
        shell: powershell
        run: |             
             $Token = 'XXXusernameXXX:${{ secrets.ACTIONS_TOKEN }}'
             $Base64Token = [System.Convert]::ToBase64String([char[]]$Token);
             $Headers = @{
                Authorization = 'Basic {0}' -f $Base64Token;
             }
             Invoke-WebRequest -Headers $Headers -Uri ${{needs.GetDownloadURL.outputs.url}} -Method Get -OutFile "${{ steps.current-artifact.outputs.CURRENT_ARTIFACT }}.zip"
        
      - name: Deploy with PowerShell
        if: ${{needs.GetDownloadURL.outputs.url}} != ""
        shell: powershell
        run: .\bat_scripts\xs_setup.bat ${{ github.event.inputs.versionName }} ${{ github.event.inputs.branchName }} # ${{ github.event.inputs.destinationEnv }}  # "./bat_scripts/test.bat" also can work
      - name: XUnit Test with PowerShell
        if: ${{needs.GetDownloadURL.outputs.url}} != ""
        shell: powershell
        run: .\bat_scripts\xunit_test.bat # "./bat_scripts/test.bat" also can work
