$time = Get-Date -Format "yyyyMMddHHmm"
Start-Transcript -Path "C:\Program Files\app\logs\XStorePOS_BigFix_Deploy.$time.log" -IncludeInvocationHeader -NoClobber

$ARTIFACT_NAME=$args[0]
$INSTALLATION_TYPE=$args[1]
$XVERSION=$args[2]
$CUSTVERSION=$args[3]
$COUNTRY=$args[4]

#PUT OFF XSTORE ARCHIVE FROM ARTIFACT
$version = "$XVERSION"+"_$CUSTVERSION"
$archivename = "XStorePOS"
Expand-Archive -LiteralPath "C:\WORKINGFOLDER\download\$ARTIFACT_NAME.zip" -DestinationPath "C:\WORKINGFOLDER"
$xstorepos = "C:\WORKINGFOLDER\OracleRetailXstorePointofService_$XVERSION"+"_AMP_$CUSTVERSION.zip"
#END PUT OFF XSTORE ARCHIVE FROM ARTIFACT

#POWERSHELL SCRIPT
$pwshscript = "C:\WORKINGFOLDER\xs.bfdeploy.ps1"
#END POWERSHELL SCRIPT

#PROPERTIES FILE
$TEMPLATE_FILE_LOCATION = 'C:\WORKINGFOLDER\bftemplate.properties'
$template_ht = ConvertFrom-StringData (Get-Content -Raw $TEMPLATE_FILE_LOCATION)
$modified_template_ht = ConvertFrom-StringData (Get-Content -Raw $TEMPLATE_FILE_LOCATION)

foreach ($key in $template_ht.Keys) {
    switch -CaseSensitive ( $key ) {
        'country'           { $modified_template_ht[$key] = $COUNTRY }
        'installation.type' { $modified_template_ht[$key] = $INSTALLATION_TYPE }
        'package.name'      { $modified_template_ht[$key] = $archivename }
        'package.version'   { $modified_template_ht[$key] = $version }
	'x.version'	    { $modified_template_ht[$key] = $XVERSION }
	'cust.version'	    { $modified_template_ht[$key] = $CUSTVERSION }
        default             { if ($modified_template_ht[$key] -eq "") { Write-Error "ERROR: The field '$key' must be filled in!"} else {continue} }
    }
}

Set-Content $TEMPLATE_FILE_LOCATION -Value $( 
	foreach ($key in $modified_template_ht.Keys) {
		'{0} = {1}' -f $key, $modified_template_ht[$key].Replace('\\', '\')
	}
)

$b = Get-Content -Path $TEMPLATE_FILE_LOCATION
@(ForEach ($a in $b) {$a.Replace(' ', '')}) > $TEMPLATE_FILE_LOCATION

Rename-Item -Path $TEMPLATE_FILE_LOCATION -NewName "bigfix.properties"
$propertiesfile = "C:\WORKINGFOLDER\bigfix.properties"
#END PROPERTIES FILE

#CREATE ARCHIVE
Compress-Archive -LiteralPath $xstorepos, $pwshscript -DestinationPath "C:\WORKINGFOLDER\$archivename" -Force
#END CREATE ARCHIVE

#COPY ARCHIVE IN SHARING DIR
Copy-Item "C:\WORKINGFOLDER\$archivename.zip" -Destination "C:\SHARING"
Copy-Item $propertiesfile -Destination "C:\SHARING"
#END COPY ARCHIVE IN SHARING DIR

Stop-Transcript
