# This file contains all properties needed for BigFix Deploy automation.

country=

#Installation
installation.type=
x.version=
cust.version=

#XStore Package
package.name=
package.version=

#Prerequisites
java.version=11
oracle.version=19.3
oracle.installation.path=C:\\PROGRA~1\\app\\oracle\\database
java.installation.path=C:\\PROGRA~1\\app\\jre

#Registry Keys
xstore.registry.key=HKLM:\\Software\\XStorePOS\\xstore
xenvironment.registry.key=HKLM:\\Software\\XStorePOS\\xenvironment
xstore.key.property=Version
xenvironment.key.property=Version
oracle.registry.key=HKLM:\\SOFTWARE\\ORACLE\\KEY_OraDB19Home1
