name: WM Build&Deploy
on:
  workflow_dispatch
  
jobs:
  GetCurrentDate:
    name: GetCurrentDate
    runs-on: windows-latest
    defaults:
        run:
            shell: powershell
            
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=DATE::$(date +'%Y-%m-%dT%H:%M')"
            echo $(date +'%Y-%m-%dT%H:%M')
