name: Lettura Exit Code

on:
  workflow_dispatch:
#    inputs:
#      versionName:
#        description: 'Name of version (ie 5.5.0)'
#        required: true
#      branchName:
#        description: 'Name of branch to deploy'
#        required: true
#      destinationEnv:
#        description: 'Name of destination Branch'
#        required: true
        
jobs:
  PrintCode:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Run Bat
        id: bat
        shell: pwsh
        run: |
             $EXIT_CODE = "$(cat .\bat_scripts\exit_code.bat)"
             echo "::set-output name=RESULT_EXIT_CODE::$EXIT_CODE"
   
      - name: Print Code
        id: print
        shell: pwsh
        if: ${{env.EXIT_CODE== '0'}}
        run: |
             echo "EXIT CODE: ${{steps.bat.outputs.RESULT_EXIT_CODE}}"
