name: Checkout

on:
  workflow_dispatch:
#    inputs:
#      versionName:
#        description: 'Name of version (ie 5.5.0)'
#        required: true
#      branchName:
#        description: 'Name of branch to deploy'
#        required: true
#      destinationEnv:
#        description: 'Name of destination Branch'
#        required: true
        
jobs:
  CheckoutExternalRepo:
    runs-on: windows-latest
    
    steps:
      - name: Checkout external repo
        uses: actions/checkout@main
        with:
          repository: MattMod/External-Repo
          token: ${{ secrets.PAT_REPO }}
